name: "Sync labels"

on:
  push:
    paths:
      - '.github/labels.yml'
      - '.github/workflows/call-label-syncer.yml'
    branches:
      - main
jobs:
  build:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1.3.0
        with:
            manifest: .github/labels.yml
            repository: |
                plan4better/goat
                plan4better/infra
                plan4better/goat-accounts
                plan4better/goat-gepapi
                plan4better/goat-core
                plan4better/goat-docs
                plan4better/goat-frontend
                plan4better/ums
            token: ${{ secrets.PAT }}