name: "PR Base"

on:
  workflow_call:

jobs:
  apply-issue-labels-on-pr:
    if: ${{ github.event_name == 'pull_request_target' && github.event.action == 'opened' }}
    name: apply-issue-labels-on-pr
    uses: "plan4better/.github/.github/workflows/pr-apply-issue-labels.yml@main"
    permissions:
      contents: none
      issues: read
      pull-requests: write
    secrets: inherit
  
  semantic-pr:
    if: ${{ github.event_name == 'pull_request_target' && contains(fromJson('["opened", "reopened", "edited", "synchronize"]'), github.event.action) }}
    name: semantic-pr
    uses: "plan4better/.github/.github/workflows/semantic-pr.yml@main"
    permissions:
      contents: none
      issues: read
      pull-requests: write
    secrets: inherit

  clean-pr-cache:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    name: clean-pr-cache
    uses: "plan4better/.github/.github/workflows/pr-cache-clean.yml@main"
    permissions:
      contents: none
      actions: write
    secrets: inherit

  welcome-new-contributors:
    if: ${{ github.event_name == 'pull_request_target' && github.event.action == 'opened' }}
    name: welcome-new-contributors
    uses: "plan4better/.github/.github/workflows/welcome-new-contributors.yml@main"
    permissions:
      contents: none
      issues: read
      pull-requests: write
    secrets: inherit
