name: "Welcome new contributors"

on:
  workflow_call:

jobs:
  welcome-message:
    name: Welcoming New Users
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.action == 'opened'
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Thank you for making your first Pull Request and taking the time to improve GOAT! 🎉
          issue-message: |
            Thank you for opening your first issue, one of our team members will review it as soon as it possible. ❤️🎉